### foundation
sample_fps: 2
max_num_frames: 1024
tokens_per_frame: 210 #210/182

### flexmem
chunk_size: 8 # Frames number of a chunk
preblk: 12 # Number of prefill memory chunks
preratio: 4 #  Compression rate of prefill memory 用于滚动上下文，继续理解后续视频块
decratio: 2 # Compression rate of decoding memory 用于回答生成，保存到视觉记忆仓库
topb: 16 # Number of chunks retrieved during decoding

