### foundation
sample_fps: 0.5
max_num_frames: 512
tokens_per_frame: 210 #210/182

### flexmem
chunk_size: 8 # Frames number of a chunk
preblk: 12 # Number of prefill memory chunks
preratio: 4 #  Compression rate of prefill memory
decratio: 4 # Compression rate of decoding memory
topb: 32 # Number of chunks retrieved during decoding
